# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchCalculationsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchCalculationsPage(object):
    def setupUi(self, BatchCalculationsPage):
        BatchCalculationsPage.setObjectName("BatchCalculationsPage")
        BatchCalculationsPage.resize(1000, 658)
        BatchCalculationsPage.setMinimumSize(QtCore.QSize(1000, 300))
        BatchCalculationsPage.setMaximumSize(QtCore.QSize(1000, 9999))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        BatchCalculationsPage.setFont(font)
        BatchCalculationsPage.setStyleSheet("QWidget{background-color: #0D1321;};")

        self.retranslateUi(BatchCalculationsPage)
        QtCore.QMetaObject.connectSlotsByName(BatchCalculationsPage)

    def retranslateUi(self, BatchCalculationsPage):
        _translate = QtCore.QCoreApplication.translate
        BatchCalculationsPage.setWindowTitle(_translate("BatchCalculationsPage", "Form"))
import HEACalculator_rc
