# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converterPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConverterPage(object):
    def setupUi(self, ConverterPage):
        ConverterPage.setObjectName("ConverterPage")
        ConverterPage.resize(1000, 658)
        ConverterPage.setMinimumSize(QtCore.QSize(1000, 300))
        ConverterPage.setMaximumSize(QtCore.QSize(1000, 9999))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        ConverterPage.setFont(font)
        ConverterPage.setStyleSheet("QWidget{background-color: #0D1321;};")

        self.retranslateUi(ConverterPage)
        QtCore.QMetaObject.connectSlotsByName(ConverterPage)

    def retranslateUi(self, ConverterPage):
        _translate = QtCore.QCoreApplication.translate
        ConverterPage.setWindowTitle(_translate("ConverterPage", "Form"))
import HEACalculator_rc
