name: Build GitHub Pages

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Deploy documentation to GitHub Pages
        run: uv run mkdocs gh-deploy --force
